language: python
env:
    - TOXENV=py26-r1
    - TOXENV=py26-r2
    - TOXENV=py27-r1
    - TOXENV=py27-r2
    - TOXENV=cov
matrix:
    allow_failures:
        - env: TOXENV=cov
install:
    - pip install --quiet --use-mirrors tox
script:
    - tox
after_script:
    - if [ $TOXENV == "cov" ]; then
      pip install --quiet --use-mirrors coveralls;
      coveralls;
      fi
